//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreestyleOnline.Pages {
    
    
    public partial class WrittenBattles {
        
        /// <summary>
        /// votetab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl votetab;
        
        /// <summary>
        /// statstab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statstab;
        
        /// <summary>
        /// User1Panel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl User1Panel;
        
        /// <summary>
        /// BattleUser1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FreestyleOnline.Controls.ProfileLink BattleUser1;
        
        /// <summary>
        /// WrittenVoteGraph1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FreestyleOnline.Controls.RapBattleVotingGraph WrittenVoteGraph1;
        
        /// <summary>
        /// BattleTextArea1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTextArea BattleTextArea1;
        
        /// <summary>
        /// BattleSubmit1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button BattleSubmit1;
        
        /// <summary>
        /// TimerIcon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Label TimerIcon;
        
        /// <summary>
        /// WrittenTimer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FreestyleOnline.Controls.CountDown WrittenTimer;
        
        /// <summary>
        /// User2Panel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl User2Panel;
        
        /// <summary>
        /// BattleJoin2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button BattleJoin2;
        
        /// <summary>
        /// BattleUser2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FreestyleOnline.Controls.ProfileLink BattleUser2;
        
        /// <summary>
        /// WrittenVoteGraph2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FreestyleOnline.Controls.RapBattleVotingGraph WrittenVoteGraph2;
        
        /// <summary>
        /// BattleTextArea2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTextArea BattleTextArea2;
        
        /// <summary>
        /// BattleSubmit2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ext.Net.Button BattleSubmit2;
        
        /// <summary>
        /// WrittenBattleComments1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FreestyleOnline.Controls.WrittenBattleComments WrittenBattleComments1;
        
        /// <summary>
        /// WrittenVote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FreestyleOnline.Controls.BattleVote WrittenVote;
        
        /// <summary>
        /// WrittenVoteDisplay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FreestyleOnline.Controls.BattleVoteDisplay WrittenVoteDisplay;
    }
}
